#' apports_nut_alim
#'
#' Data inca3.
#'
#' @format A data frame with 4114 rows and 108 variables:
#' \describe{
#'   \item{ POPULATION }{  character }
#'   \item{ NOIND }{  numeric }
#'   \item{ nutriment1 }{  numeric }
#'   \item{ nutriment2 }{  numeric }
#'   \item{ nutriment3 }{  numeric }
#'   \item{ nutriment4 }{  numeric }
#'   \item{ nutriment5 }{  numeric }
#'   \item{ nutriment6 }{  numeric }
#'   \item{ nutriment7 }{  numeric }
#'   \item{ nutriment8 }{  numeric }
#'   \item{ nutriment9 }{  numeric }
#'   \item{ nutriment10 }{  numeric }
#'   \item{ nutriment11 }{  numeric }
#'   \item{ nutriment12 }{  numeric }
#'   \item{ nutriment13 }{  numeric }
#'   \item{ nutriment14 }{  numeric }
#'   \item{ nutriment15 }{  numeric }
#'   \item{ nutriment16 }{  numeric }
#'   \item{ nutriment17 }{  numeric }
#'   \item{ nutriment18 }{  numeric }
#'   \item{ nutriment19 }{  numeric }
#'   \item{ nutriment20 }{  numeric }
#'   \item{ nutriment21 }{  numeric }
#'   \item{ nutriment22 }{  numeric }
#'   \item{ nutriment23 }{  numeric }
#'   \item{ nutriment24 }{  numeric }
#'   \item{ nutriment25 }{  numeric }
#'   \item{ nutriment26 }{  numeric }
#'   \item{ nutriment27 }{  numeric }
#'   \item{ nutriment28 }{  numeric }
#'   \item{ nutriment29 }{  numeric }
#'   \item{ nutriment30 }{  numeric }
#'   \item{ nutriment31 }{  numeric }
#'   \item{ nutriment32 }{  numeric }
#'   \item{ nutriment33 }{  numeric }
#'   \item{ nutriment34 }{  numeric }
#'   \item{ nutriment35 }{  numeric }
#'   \item{ nutriment36 }{  numeric }
#'   \item{ nutriment37 }{  numeric }
#'   \item{ nutriment38 }{  numeric }
#'   \item{ nutriment39 }{  numeric }
#'   \item{ nutriment40 }{  numeric }
#'   \item{ nutriment41 }{  numeric }
#'   \item{ nutriment42 }{  numeric }
#'   \item{ nutriment43 }{  numeric }
#'   \item{ nutriment44 }{  numeric }
#'   \item{ nutriment45 }{  numeric }
#'   \item{ nutriment46 }{  numeric }
#'   \item{ nutriment47 }{  numeric }
#'   \item{ nutriment48 }{  numeric }
#'   \item{ nutriment49 }{  numeric }
#'   \item{ nutriment50 }{  numeric }
#'   \item{ nutriment51 }{  numeric }
#'   \item{ nutriment52 }{  numeric }
#'   \item{ nutriment53 }{  numeric }
#'   \item{ nutriment54 }{  numeric }
#'   \item{ contrib3 }{  numeric }
#'   \item{ contrib4 }{  numeric }
#'   \item{ contrib5 }{  numeric }
#'   \item{ contrib6 }{  numeric }
#'   \item{ contrib7 }{  numeric }
#'   \item{ contrib8 }{  numeric }
#'   \item{ contrib9 }{  numeric }
#'   \item{ contrib10 }{  numeric }
#'   \item{ contrib11 }{  numeric }
#'   \item{ contrib12 }{  numeric }
#'   \item{ contrib13 }{  numeric }
#'   \item{ contrib14 }{  numeric }
#'   \item{ contrib15 }{  numeric }
#'   \item{ contrib16 }{  numeric }
#'   \item{ contrib17 }{  numeric }
#'   \item{ contrib18 }{  numeric }
#'   \item{ contrib19 }{  numeric }
#'   \item{ contrib20 }{  numeric }
#'   \item{ contrib21 }{  numeric }
#'   \item{ contrib22 }{  numeric }
#'   \item{ contrib23 }{  numeric }
#'   \item{ contrib24 }{  numeric }
#'   \item{ contrib25 }{  numeric }
#'   \item{ contrib26 }{  numeric }
#'   \item{ contrib27 }{  numeric }
#'   \item{ contrib28 }{  numeric }
#'   \item{ contrib29 }{  numeric }
#'   \item{ contrib30 }{  numeric }
#'   \item{ contrib31 }{  numeric }
#'   \item{ contrib32 }{  numeric }
#'   \item{ contrib33 }{  numeric }
#'   \item{ contrib34 }{  numeric }
#'   \item{ contrib35 }{  numeric }
#'   \item{ contrib36 }{  numeric }
#'   \item{ contrib37 }{  numeric }
#'   \item{ contrib38 }{  numeric }
#'   \item{ contrib39 }{  numeric }
#'   \item{ contrib40 }{  numeric }
#'   \item{ contrib41 }{  numeric }
#'   \item{ contrib42 }{  numeric }
#'   \item{ contrib43 }{  numeric }
#'   \item{ contrib44 }{  numeric }
#'   \item{ contrib45 }{  numeric }
#'   \item{ contrib46 }{  numeric }
#'   \item{ contrib47 }{  numeric }
#'   \item{ contrib48 }{  numeric }
#'   \item{ contrib49 }{  numeric }
#'   \item{ contrib50 }{  numeric }
#'   \item{ contrib51 }{  numeric }
#'   \item{ contrib52 }{  numeric }
#'   \item{ contrib53 }{  numeric }
#'   \item{ contrib54 }{  numeric }
#' }
#' @source Inca3
"apports_nut_alim"
