#' conso_compo_alim_decode
#'
#' Data inca3.
#'
#' @format A data frame with 256301 rows and 109 variables:
#' \describe{
#'   \item{ POPULATION }{  character }
#'   \item{ NOIND }{  numeric }
#'   \item{ NUM_LIGNE }{  numeric }
#'   \item{ R24_num }{  character }
#'   \item{ R24_nombre }{  numeric }
#'   \item{ R24_pond }{  numeric }
#'   \item{ occ_hdeb }{  hms,difftime }
#'   \item{ occ_type }{  character }
#'   \item{ occ_lieu }{  character }
#'   \item{ occ_alim_libelle }{  character }
#'   \item{ occ_alim_num }{  numeric }
#'   \item{ occ_alim_num_seq }{  numeric }
#'   \item{ gpe_INCA3 }{  character }
#'   \item{ aliment_code_INCA3 }{  numeric }
#'   \item{ aliment_libelle_INCA3 }{  character }
#'   \item{ aliment_code_FX }{  character }
#'   \item{ aliment_libelle_FX }{  character }
#'   \item{ qte_conso }{  numeric }
#'   \item{ qte_conso_pond }{  numeric }
#'   \item{ facette_01 }{  character }
#'   \item{ facette_01_libelle }{  character }
#'   \item{ facette_02 }{  character }
#'   \item{ facette_02_libelle }{  character }
#'   \item{ facette_03 }{  character }
#'   \item{ facette_03_libelle }{  character }
#'   \item{ facette_04 }{  character }
#'   \item{ facette_04_libelle }{  character }
#'   \item{ facette_05 }{  character }
#'   \item{ facette_05_libelle }{  character }
#'   \item{ facette_06 }{  character }
#'   \item{ facette_06_libelle }{  character }
#'   \item{ facette_07 }{  character }
#'   \item{ facette_07_libelle }{  character }
#'   \item{ facette_08 }{  character }
#'   \item{ facette_08_libelle }{  character }
#'   \item{ facette_09 }{  character }
#'   \item{ facette_09_libelle }{  character }
#'   \item{ facette_10 }{  character }
#'   \item{ facette_10_libelle }{  character }
#'   \item{ facette_12 }{  character }
#'   \item{ facette_12_libelle }{  character }
#'   \item{ aliment_marque_bio }{  character }
#'   \item{ aliment_marque_enrichi }{  character }
#'   \item{ facette_13 }{  character }
#'   \item{ facette_13_libelle }{  character }
#'   \item{ facette_14 }{  character }
#'   \item{ facette_14_libelle }{  character }
#'   \item{ facette_19 }{  character }
#'   \item{ facette_19_libelle }{  character }
#'   \item{ facette_20 }{  character }
#'   \item{ facette_20_libelle }{  character }
#'   \item{ facette_25 }{  character }
#'   \item{ facette_25_libelle }{  character }
#'   \item{ facette_27 }{  character }
#'   \item{ facette_27_libelle }{  character }
#'   \item{ aet }{  numeric }
#'   \item{ aesa }{  numeric }
#'   \item{ proteines }{  numeric }
#'   \item{ glucides }{  numeric }
#'   \item{ sucres }{  numeric }
#'   \item{ amidon }{  numeric }
#'   \item{ polyols }{  numeric }
#'   \item{ fibres }{  numeric }
#'   \item{ acides_organiques }{  numeric }
#'   \item{ lipides }{  numeric }
#'   \item{ ags }{  numeric }
#'   \item{ ag_16_0 }{  numeric }
#'   \item{ ag_18_0 }{  numeric }
#'   \item{ ag_14_0 }{  numeric }
#'   \item{ ag_12_0 }{  numeric }
#'   \item{ ag_10_0 }{  numeric }
#'   \item{ ag_04_0 }{  numeric }
#'   \item{ ag_06_0 }{  numeric }
#'   \item{ ag_08_0 }{  numeric }
#'   \item{ agmi }{  numeric }
#'   \item{ ag_18_1_ole }{  numeric }
#'   \item{ agpi }{  numeric }
#'   \item{ ag_18_2_lino }{  numeric }
#'   \item{ ag_18_3_a_lino }{  numeric }
#'   \item{ ag_20_4_ara }{  numeric }
#'   \item{ ag_20_5_epa }{  numeric }
#'   \item{ ag_20_6_dha }{  numeric }
#'   \item{ alcool }{  numeric }
#'   \item{ eau }{  numeric }
#'   \item{ retinol }{  numeric }
#'   \item{ beta_carotene }{  numeric }
#'   \item{ vitamine_b1 }{  numeric }
#'   \item{ vitamine_b2 }{  numeric }
#'   \item{ vitamine_b3 }{  numeric }
#'   \item{ vitamine_b5 }{  numeric }
#'   \item{ vitamine_b6 }{  numeric }
#'   \item{ vitamine_b9 }{  numeric }
#'   \item{ vitamine_b12 }{  numeric }
#'   \item{ vitamine_c }{  numeric }
#'   \item{ vitamine_d }{  numeric }
#'   \item{ vitamine_e }{  numeric }
#'   \item{ vitamine_k2 }{  numeric }
#'   \item{ sodium }{  numeric }
#'   \item{ sel }{  numeric }
#'   \item{ magnesium }{  numeric }
#'   \item{ phosphore }{  numeric }
#'   \item{ potassium }{  numeric }
#'   \item{ calcium }{  numeric }
#'   \item{ manganese }{  numeric }
#'   \item{ fer }{  numeric }
#'   \item{ cuivre }{  numeric }
#'   \item{ zinc }{  numeric }
#'   \item{ selenium }{  numeric }
#'   \item{ iode }{  numeric }
#' }
#' @source Inca3
"conso_compo_alim_decode"
