#' habitudes_indiv_decode
#'
#' Data inca3.
#'
#' @format A data frame with 4372 rows and 389 variables:
#' \describe{
#'   \item{ POPULATION }{  character }
#'   \item{ NOIND }{  numeric }
#'   \item{ periode_reference }{  character }
#'   \item{ repasenfantmidi_vous }{  character }
#'   \item{ repasenfantmidi_am }{  character }
#'   \item{ repasenfantmidi_creche }{  character }
#'   \item{ repasenfantmidi_parent }{  character }
#'   \item{ repasenfantmidi_autre }{  character }
#'   \item{ repasenfantmidi_autre_libelle }{  logical }
#'   \item{ repasenfant_freq }{  character }
#'   \item{ conso_bebe_sein }{  character }
#'   \item{ lait_plussouvent }{  character }
#'   \item{ lait_plusvt_li_autr_anim_libelle }{  logical }
#'   \item{ lait_plusvt_pi_autre_veg_libelle }{  logical }
#'   \item{ lait_plusvt_boisson_veg_libelle }{  character }
#'   \item{ lait_plusvt_autre_anim_libelle }{  logical }
#'   \item{ lait_plusvt_autre_libelle }{  logical }
#'   \item{ lait_occ_laitmaternel }{  character }
#'   \item{ lait_occ_lait_1e_age }{  character }
#'   \item{ lait_occ_lait_2e_age }{  character }
#'   \item{ lait_occ_lait_croissance }{  character }
#'   \item{ lait_occ_li_autre_anim }{  character }
#'   \item{ lait_occ_li_autre_anim_libelle }{  logical }
#'   \item{ lait_occ_li1e_age_protsoja }{  character }
#'   \item{ lait_occ_li2e_age_protsoja }{  character }
#'   \item{ lait_occ_soja_croissance }{  character }
#'   \item{ lait_occ_li1e_age_protriz }{  character }
#'   \item{ lait_occ_li2e_age_protriz }{  character }
#'   \item{ lait_occ_riz_croissance }{  character }
#'   \item{ lait_occ_pi_autre_veg }{  character }
#'   \item{ lait_occ_pi_autre_veg_libelle }{  logical }
#'   \item{ lait_occ_boisson_lait_bebe }{  character }
#'   \item{ lait_occ_lait_regime_infantile }{  character }
#'   \item{ lait_occ_lait_vache }{  character }
#'   \item{ lait_occ_boisson_soja }{  character }
#'   \item{ lait_occ_boisson_veg }{  character }
#'   \item{ lait_occ_boisson_veg_libelle }{  logical }
#'   \item{ lait_occ_autre_anim }{  character }
#'   \item{ lait_occ_autre_anim_libelle }{  logical }
#'   \item{ lait_occ_autre }{  character }
#'   \item{ lait_occ_autre_libelle }{  logical }
#'   \item{ lait_occ_aucun }{  character }
#'   \item{ lait_occ_nsp }{  character }
#'   \item{ etablissement_scolaire }{  character }
#'   \item{ lieu_repas_midi }{  character }
#'   \item{ lieu_repas_midi_autre_libelle }{  character }
#'   \item{ cantine_freq }{  character }
#'   \item{ cantine_jms_persfoyer }{  character }
#'   \item{ cantine_jms_veutpas }{  character }
#'   \item{ cantine_jms_probsante }{  character }
#'   \item{ cantine_jms_repaspasequilibre }{  character }
#'   \item{ cantine_jms_repaspasqualite }{  character }
#'   \item{ cantine_jms_repaschers }{  character }
#'   \item{ cantine_jms_ecoleproche }{  character }
#'   \item{ cantine_jms_paspropose }{  character }
#'   \item{ cantine_jms_pasaime }{  character }
#'   \item{ cantine_jms_autre_raison }{  character }
#'   \item{ cantine_jms_autre_raison_libelle }{  character }
#'   \item{ cantine_jms_nsp }{  character }
#'   \item{ collation_freq }{  character }
#'   \item{ collation_aliment1 }{  character }
#'   \item{ collation_aliment2 }{  character }
#'   \item{ collation_aliment3 }{  character }
#'   \item{ collation_aliment4 }{  character }
#'   \item{ collation_matin_freq }{  character }
#'   \item{ collation_matin_ecole_freq }{  character }
#'   \item{ collation_matin_pasecole_freq }{  character }
#'   \item{ collation_matin_aliment1 }{  character }
#'   \item{ collation_matin_aliment2 }{  character }
#'   \item{ collation_matin_aliment3 }{  character }
#'   \item{ collation_matin_aliment4 }{  character }
#'   \item{ distributeur_freq }{  character }
#'   \item{ distributeur_biscuits_sales }{  character }
#'   \item{ distributeur_biscuits_sucres }{  character }
#'   \item{ distributeur_barres_choco }{  character }
#'   \item{ distributeur_confiseries }{  character }
#'   \item{ distributeur_fruits_frais }{  character }
#'   \item{ distributeur_jus_de_fruits }{  character }
#'   \item{ distributeur_boissons_energ }{  character }
#'   \item{ distributeur_sodas }{  character }
#'   \item{ distributeur_eaux }{  character }
#'   \item{ distributeur_autre }{  character }
#'   \item{ distributeur_autre_libelle }{  character }
#'   \item{ distributeur_nsp }{  character }
#'   \item{ restaurationrapide_freq }{  character }
#'   \item{ aime_legumes }{  character }
#'   \item{ aime_viande }{  character }
#'   \item{ aime_fruits }{  character }
#'   \item{ aime_glaces }{  character }
#'   \item{ aime_fromage }{  character }
#'   \item{ aime_poisson }{  character }
#'   \item{ aime_soda }{  character }
#'   \item{ aime_lait }{  character }
#'   \item{ aime_yaourts }{  character }
#'   \item{ aime_jus_de_fruits }{  character }
#'   \item{ table_beurre }{  character }
#'   \item{ table_creme_fraiche }{  character }
#'   \item{ table_huile_olive }{  character }
#'   \item{ table_vinaigrette }{  character }
#'   \item{ table_mayonnaise }{  character }
#'   \item{ table_ketchup }{  character }
#'   \item{ table_sauce_soja }{  character }
#'   \item{ table_sel }{  character }
#'   \item{ etiquette_freq }{  character }
#'   \item{ etiquette_ingredients }{  character }
#'   \item{ etiquette_contenu_nutri }{  character }
#'   \item{ etiquette_portions }{  character }
#'   \item{ etiquette_message_nutri }{  character }
#'   \item{ etiquette_effets_benefiques }{  character }
#'   \item{ source_medecins }{  character }
#'   \item{ source_personnels_pharma }{  character }
#'   \item{ source_publicite }{  character }
#'   \item{ source_emissions_info }{  character }
#'   \item{ source_journaux }{  character }
#'   \item{ source_livres }{  character }
#'   \item{ source_professeurs }{  character }
#'   \item{ source_famille }{  character }
#'   \item{ source_amis }{  character }
#'   \item{ source_internet }{  character }
#'   \item{ source_emballages }{  character }
#'   \item{ source_autre }{  character }
#'   \item{ source_autre_libelle }{  character }
#'   \item{ conso_lardons_crus }{  character }
#'   \item{ conso_saucisses_crues }{  character }
#'   \item{ conso_viande_boeuf_crue }{  character }
#'   \item{ conso_viande_cheval_crue }{  character }
#'   \item{ conso_viande_porc_crue }{  character }
#'   \item{ conso_viande_volaille_crue }{  character }
#'   \item{ conso_poisson_cru }{  character }
#'   \item{ conso_mollusques_crus }{  character }
#'   \item{ conso_oeufs_crus }{  character }
#'   \item{ conso_croute_fleurie }{  character }
#'   \item{ conso_croute_lavee }{  character }
#'   \item{ conso_pate_pressee_non_cuite }{  character }
#'   \item{ conso_pate_pressee_cuite }{  character }
#'   \item{ conso_pate_persillee }{  character }
#'   \item{ pomme_crue_lave }{  character }
#'   \item{ pomme_crue_essuie }{  character }
#'   \item{ pomme_crue_epluche }{  character }
#'   \item{ pomme_crue_rien }{  character }
#'   \item{ pomme_crue_mange_pas }{  character }
#'   \item{ peche_crue_lave }{  character }
#'   \item{ peche_crue_essuie }{  character }
#'   \item{ peche_crue_epluche }{  character }
#'   \item{ peche_crue_rien }{  character }
#'   \item{ peche_crue_mange_pas }{  character }
#'   \item{ raisin_cru_lave }{  character }
#'   \item{ raisin_cru_essuie }{  character }
#'   \item{ raisin_cru_epluche }{  character }
#'   \item{ raisin_cru_rien }{  character }
#'   \item{ raisin_cru_mange_pas }{  character }
#'   \item{ fraise_crue_lave }{  character }
#'   \item{ fraise_crue_essuie }{  character }
#'   \item{ fraise_crue_epluche }{  character }
#'   \item{ fraise_crue_rien }{  character }
#'   \item{ fraise_crue_mange_pas }{  character }
#'   \item{ tomate_crue_lave }{  character }
#'   \item{ tomate_crue_essuie }{  character }
#'   \item{ tomate_crue_epluche }{  character }
#'   \item{ tomate_crue_rien }{  character }
#'   \item{ tomate_crue_mange_pas }{  character }
#'   \item{ champignon_cru_lave }{  character }
#'   \item{ champignon_cru_essuie }{  character }
#'   \item{ champignon_cru_epluche }{  character }
#'   \item{ champignon_cru_rien }{  character }
#'   \item{ champignon_cru_mange_pas }{  character }
#'   \item{ salade_crue_lave }{  character }
#'   \item{ salade_crue_essuie }{  character }
#'   \item{ salade_crue_epluche }{  character }
#'   \item{ salade_crue_rien }{  character }
#'   \item{ salade_crue_mange_pas }{  character }
#'   \item{ concombre_cru_lave }{  character }
#'   \item{ concombre_cru_essuie }{  character }
#'   \item{ concombre_cru_epluche }{  character }
#'   \item{ concombre_cru_rien }{  character }
#'   \item{ concombre_cru_mange_pas }{  character }
#'   \item{ utilisation_bib }{  character }
#'   \item{ bib_plastique }{  character }
#'   \item{ bib_verre }{  character }
#'   \item{ bib_nsp }{  character }
#'   \item{ sterilisation_bib }{  character }
#'   \item{ sterilisation_bib_libelle }{  character }
#'   \item{ tetine_caoutchouc }{  character }
#'   \item{ tetine_silicone }{  character }
#'   \item{ tetine_nsp }{  character }
#'   \item{ sterilisation_tetine }{  character }
#'   \item{ sterilisation_tetine_libelle }{  character }
#'   \item{ bib_lm }{  character }
#'   \item{ bib_li }{  character }
#'   \item{ bib_lc }{  character }
#'   \item{ bib_bl }{  character }
#'   \item{ bib_ppl }{  character }
#'   \item{ bib_eau }{  character }
#'   \item{ bib_jus }{  character }
#'   \item{ bib_autre }{  character }
#'   \item{ bib_autre_libelle }{  logical }
#'   \item{ stockage_bib_lm }{  character }
#'   \item{ delai_conso_bib_lm }{  character }
#'   \item{ prepa_bib_li }{  character }
#'   \item{ conserv_eau }{  character }
#'   \item{ conserv_eau_libelle }{  logical }
#'   \item{ reste_eau }{  character }
#'   \item{ conso_apres_prepa_bib_li }{  character }
#'   \item{ tps_conserv_bib_li }{  character }
#'   \item{ lieu_conserv_bib_li }{  character }
#'   \item{ lieu_conserv_bib_li_libelle }{  logical }
#'   \item{ tps_conso_bib_li }{  character }
#'   \item{ chauffe_lm }{  character }
#'   \item{ chauffe_pi }{  character }
#'   \item{ chauffe_lc }{  character }
#'   \item{ chauffe_bl }{  character }
#'   \item{ bib_micro_ondes }{  character }
#'   \item{ bib_chauffe_bib }{  character }
#'   \item{ bib_bainmarie }{  character }
#'   \item{ diversification_alim_bebe }{  character }
#'   \item{ prepbb }{  character }
#'   \item{ prepbb_chauff }{  character }
#'   \item{ prepbb_chauff_coupplastique }{  character }
#'   \item{ prepbb_chauff_potverre }{  character }
#'   \item{ prepbb_chauff_recipopaque }{  character }
#'   \item{ prepbb_chauff_reciptranslucid }{  character }
#'   \item{ prepbb_chauff_recipceramique }{  character }
#'   \item{ prepbb_chauff_recipverre }{  character }
#'   \item{ prepbb_chauff_autre }{  character }
#'   \item{ prepbb_chauff_autre_libelle }{  logical }
#'   \item{ conso_farine_ssgluten }{  character }
#'   \item{ conso_farine_ssgluten_age }{  numeric }
#'   \item{ conso_farine_ssgluten_age_nsp }{  character }
#'   \item{ conso_farine_acgluten }{  character }
#'   \item{ conso_farine_acgluten_age }{  numeric }
#'   \item{ conso_farine_acgluten_age_nsp }{  character }
#'   \item{ conso_cereales }{  character }
#'   \item{ conso_cereales_age }{  numeric }
#'   \item{ conso_cereales_age_nsp }{  character }
#'   \item{ conso_legumes_horspdt }{  character }
#'   \item{ conso_legumes_horspdt_age }{  numeric }
#'   \item{ conso_legumes_horspdt_age_nsp }{  character }
#'   \item{ conso_pdt }{  character }
#'   \item{ conso_pdt_age }{  numeric }
#'   \item{ conso_pdt_age_nsp }{  character }
#'   \item{ conso_riz_pates }{  character }
#'   \item{ conso_riz_pates_age }{  numeric }
#'   \item{ conso_riz_pates_age_nsp }{  character }
#'   \item{ conso_fruits }{  character }
#'   \item{ conso_fruits_age }{  numeric }
#'   \item{ conso_fruits_age_nsp }{  character }
#'   \item{ conso_yaourts }{  character }
#'   \item{ conso_yaourts_age }{  numeric }
#'   \item{ conso_yaourts_age_nsp }{  character }
#'   \item{ conso_autres_desserts }{  character }
#'   \item{ conso_autres_desserts_age }{  numeric }
#'   \item{ conso_autres_desserts_age_nsp }{  character }
#'   \item{ conso_fromage }{  character }
#'   \item{ conso_fromage_age }{  numeric }
#'   \item{ conso_fromage_age_nsp }{  character }
#'   \item{ conso_viande }{  character }
#'   \item{ conso_viande_age }{  numeric }
#'   \item{ conso_viande_age_nsp }{  character }
#'   \item{ conso_poisson }{  character }
#'   \item{ conso_poisson_age }{  numeric }
#'   \item{ conso_poisson_age_nsp }{  character }
#'   \item{ conso_jambon }{  character }
#'   \item{ conso_jambon_age }{  numeric }
#'   \item{ conso_jambon_age_nsp }{  character }
#'   \item{ conso_oeufs }{  character }
#'   \item{ conso_oeufs_age }{  numeric }
#'   \item{ conso_oeufs_age_nsp }{  character }
#'   \item{ conso_gateaux }{  character }
#'   \item{ conso_gateaux_age }{  numeric }
#'   \item{ conso_gateaux_age_nsp }{  character }
#'   \item{ conso_pain }{  character }
#'   \item{ conso_pain_age }{  numeric }
#'   \item{ conso_pain_age_nsp }{  character }
#'   \item{ conso_jus }{  character }
#'   \item{ conso_jus_age }{  numeric }
#'   \item{ conso_jus_age_nsp }{  character }
#'   \item{ conso_autres }{  character }
#'   \item{ conso_autres_age }{  logical }
#'   \item{ conso_autres_age_nsp }{  character }
#'   \item{ conso_autres_libelle }{  logical }
#'   \item{ conso_nsp }{  character }
#'   \item{ conso_plats_faits_maison }{  character }
#'   \item{ jardin }{  character }
#'   \item{ jardin_potager }{  character }
#'   \item{ jardin_arbres_fruitiers }{  character }
#'   \item{ jardin_poulailler }{  character }
#'   \item{ jardin_clapier }{  character }
#'   \item{ jardin_fleurs }{  character }
#'   \item{ jardin_rien }{  character }
#'   \item{ jardin_entretien }{  character }
#'   \item{ autoproduction_aliments }{  character }
#'   \item{ autoproduction_oeufs_freq }{  character }
#'   \item{ autoproduction_volailles_freq }{  character }
#'   \item{ autoproduction_volailles_libelle }{  character }
#'   \item{ autoproduction_lapins_freq }{  character }
#'   \item{ autoproduction_viandes_freq }{  character }
#'   \item{ autoproduction_viandes_libelle }{  character }
#'   \item{ autoproduction_lait_freq }{  character }
#'   \item{ autoproduction_pdt_freq }{  character }
#'   \item{ autoproduction_tomates_freq }{  character }
#'   \item{ autoproduction_tomates_libelle }{  character }
#'   \item{ autoproduction_carottes_freq }{  character }
#'   \item{ autoproduction_carottes_libelle }{  character }
#'   \item{ autoproduction_salades_freq }{  character }
#'   \item{ autoproduction_salades_libelle }{  character }
#'   \item{ autoproduction_abricots_freq }{  character }
#'   \item{ autoproduction_abricots_libelle }{  character }
#'   \item{ autoproduction_pommes_freq }{  character }
#'   \item{ autoproduction_pommes_libelle }{  character }
#'   \item{ autoproduction_fraises_freq }{  character }
#'   \item{ autoproduction_fraises_libelle }{  character }
#'   \item{ autoproduction_raisins_freq }{  character }
#'   \item{ autoproduction_autresfruits_freq }{  character }
#'   \item{ autoproduction_autrfruit_libelle }{  character }
#'   \item{ autoproduction_autreslegum_freq }{  character }
#'   \item{ autoproduction_autrlegum_libelle }{  character }
#'   \item{ cueillette_fruits_freq }{  character }
#'   \item{ cueillette_champignons_freq }{  character }
#'   \item{ peche_poissons_eau_douce_freq }{  character }
#'   \item{ peche_poissons_eau_mer_freq }{  character }
#'   \item{ peche_coquillages_freq }{  character }
#'   \item{ chasse_gibiers_freq }{  character }
#'   \item{ autoconsommation }{  character }
#'   \item{ autoconsommation_type }{  character }
#'   \item{ autoproduction }{  character }
#'   \item{ cueillette }{  character }
#'   \item{ autoconso_oeufs }{  character }
#'   \item{ autoconso_oeufs_type }{  character }
#'   \item{ autoconso_viandes }{  character }
#'   \item{ autoconso_viandes_type }{  character }
#'   \item{ autoconso_volailles_tot }{  character }
#'   \item{ autoconso_volailles_tot_type }{  character }
#'   \item{ autoconso_lait }{  character }
#'   \item{ autoconso_lait_type }{  character }
#'   \item{ autoconso_pdt }{  character }
#'   \item{ autoconso_pdt_type }{  character }
#'   \item{ autoconso_legumes_tot }{  character }
#'   \item{ autoconso_legumes_tot_type }{  character }
#'   \item{ autoconso_fruits_tot }{  character }
#'   \item{ autoconso_fruits_tot_type }{  character }
#'   \item{ autoconso_pdts_mer }{  character }
#'   \item{ autoconso_pdts_mer_type }{  character }
#'   \item{ conso_aliments_bio }{  character }
#'   \item{ conso_lait_bio_freq }{  character }
#'   \item{ conso_oeufs_bio_freq }{  character }
#'   \item{ conso_volailles_bio_freq }{  character }
#'   \item{ conso_viandes_bio_freq }{  character }
#'   \item{ conso_poissons_bio_freq }{  character }
#'   \item{ conso_fruits_bio_freq }{  character }
#'   \item{ conso_fruits_bio_libelle }{  character }
#'   \item{ conso_pdt_bio_freq }{  character }
#'   \item{ conso_legumes_bio_freq }{  character }
#'   \item{ conso_legumes_bio_libelle }{  character }
#'   \item{ conso_legumes_secs_bio_freq }{  character }
#'   \item{ conso_legumes_secs_bio_libelle }{  character }
#'   \item{ conso_pain_bio_freq }{  character }
#'   \item{ conso_cereales_bio_freq }{  character }
#'   \item{ conso_cereales_bio_libelle }{  character }
#'   \item{ conso_autres_alim_bio_freq }{  character }
#'   \item{ conso_autres_alim_bio_libelle }{  character }
#'   \item{ conso_lait_bebe_bio_freq }{  character }
#'   \item{ conso_yaourt_bebe_bio_freq }{  character }
#'   \item{ conso_jus_bebe_bio_freq }{  character }
#'   \item{ conso_puree_bebe_bio_freq }{  character }
#'   \item{ conso_cereales_bebe_bio_freq }{  character }
#'   \item{ conso_biscuits_bebe_bio_freq }{  character }
#'   \item{ conso_plats_bebe_bio_freq }{  character }
#'   \item{ conso_compotes_bebe_bio_freq }{  character }
#'   \item{ conso_cremes_bebe_bio_freq }{  character }
#'   \item{ consommation_bio }{  character }
#'   \item{ consommation_bio_type }{  character }
#'   \item{ conso_oeufs_bio_tjr_svt }{  character }
#'   \item{ conso_lait_bio_tjr_svt }{  character }
#'   \item{ conso_volailles_bio_tjr_svt }{  character }
#'   \item{ conso_viandes_bio_tjr_svt }{  character }
#'   \item{ conso_poissons_bio_tjr_svt }{  character }
#'   \item{ conso_fruits_bio_tjr_svt }{  character }
#'   \item{ conso_pdt_bio_tjr_svt }{  character }
#'   \item{ conso_legumes_bio_tjr_svt }{  character }
#'   \item{ conso_legumes_secs_bio_tjr_svt }{  character }
#'   \item{ conso_cereales_bio_tjr_svt }{  character }
#'   \item{ conso_pain_bio_tjr_svt }{  character }
#'   \item{ conso_autres_alim_bio_tjr_svt }{  character }
#'   \item{ conso_barbecue }{  character }
#'   \item{ conso_barbecue_elec }{  character }
#'   \item{ conso_barbecue_bois }{  character }
#'   \item{ conso_barbecue_gaz }{  character }
#'   \item{ conso_barbecue_printps_ete_freq }{  character }
#'   \item{ conso_barbecue_automn_hiver_freq }{  character }
#' }
#' @source Inca3
"habitudes_indiv_decode"
