#' habitudes_men_decode
#'
#' Data inca3.
#'
#' @format A data frame with 4372 rows and 167 variables:
#' \describe{
#'   \item{ POPULATION }{  character }
#'   \item{ NOMEN }{  numeric }
#'   \item{ pomme_cuite_lave }{  character }
#'   \item{ pomme_cuite_essuie }{  character }
#'   \item{ pomme_cuite_epluche }{  character }
#'   \item{ pomme_cuite_rien }{  character }
#'   \item{ pomme_cuite_cuisine_pas }{  character }
#'   \item{ peche_cuite_lave }{  character }
#'   \item{ peche_cuite_essuie }{  character }
#'   \item{ peche_cuite_epluche }{  character }
#'   \item{ peche_cuite_rien }{  character }
#'   \item{ peche_cuite_cuisine_pas }{  character }
#'   \item{ raisin_cuit_lave }{  character }
#'   \item{ raisin_cuit_essuie }{  character }
#'   \item{ raisin_cuit_epluche }{  character }
#'   \item{ raisin_cuit_rien }{  character }
#'   \item{ raisin_cuit_cuisine_pas }{  character }
#'   \item{ fraise_cuite_lave }{  character }
#'   \item{ fraise_cuite_essuie }{  character }
#'   \item{ fraise_cuite_epluche }{  character }
#'   \item{ fraise_cuite_rien }{  character }
#'   \item{ fraise_cuite_cuisine_pas }{  character }
#'   \item{ tomate_cuite_lave }{  character }
#'   \item{ tomate_cuite_essuie }{  character }
#'   \item{ tomate_cuite_epluche }{  character }
#'   \item{ tomate_cuite_rien }{  character }
#'   \item{ tomate_cuite_cuisine_pas }{  character }
#'   \item{ champignon_cuit_lave }{  character }
#'   \item{ champignon_cuit_essuie }{  character }
#'   \item{ champignon_cuit_epluche }{  character }
#'   \item{ champignon_cuit_rien }{  character }
#'   \item{ champignon_cuit_cuisine_pas }{  character }
#'   \item{ chou_cuit_lave }{  character }
#'   \item{ chou_cuit_essuie }{  character }
#'   \item{ chou_cuit_epluche }{  character }
#'   \item{ chou_cuit_rien }{  character }
#'   \item{ chou_cuit_cuisine_pas }{  character }
#'   \item{ concombre_cuit_lave }{  character }
#'   \item{ concombre_cuit_essuie }{  character }
#'   \item{ concombre_cuit_epluche }{  character }
#'   \item{ concombre_cuit_rien }{  character }
#'   \item{ concombre_cuit_cuisine_pas }{  character }
#'   \item{ recip_cuisson_inox }{  character }
#'   \item{ recip_cuisson_alu }{  character }
#'   \item{ recip_cuisson_metal }{  character }
#'   \item{ recip_cuisson_ceramique }{  character }
#'   \item{ recip_cuisson_fonte }{  character }
#'   \item{ recip_cuisson_antiadhesif }{  character }
#'   \item{ recip_cuisson_autre }{  character }
#'   \item{ recip_cuisson_autre_libelle }{  character }
#'   \item{ recip_cuisson_nsp }{  character }
#'   \item{ four_ondes }{  character }
#'   \item{ four_ondes_vaisselle_maison }{  character }
#'   \item{ four_ondes_vaiss_maison_libelle }{  logical }
#'   \item{ four_ondes_vaisselle }{  character }
#'   \item{ four_ondes_vaiss_libelle }{  logical }
#'   \item{ choix_aliment_origine }{  character }
#'   \item{ choix_aliment_prix }{  character }
#'   \item{ choix_aliment_offres_promo }{  character }
#'   \item{ choix_aliment_habitude }{  character }
#'   \item{ choix_aliment_marque }{  character }
#'   \item{ choix_aliment_facilite_prepa }{  character }
#'   \item{ choix_aliment_apparence }{  character }
#'   \item{ choix_aliment_mode_prod }{  character }
#'   \item{ choix_aliment_gout }{  character }
#'   \item{ choix_aliment_prod_nouveau }{  character }
#'   \item{ choix_aliment_pub }{  character }
#'   \item{ choix_aliment_signe_quali }{  character }
#'   \item{ choix_aliment_compo_nutri }{  character }
#'   \item{ choix_aliment_ingredients }{  character }
#'   \item{ choix_aliment_raison_sante }{  character }
#'   \item{ choix_aliment_autres_infos }{  character }
#'   \item{ choix_prod_identiques }{  character }
#'   \item{ lieu_achat_fruits_frais }{  character }
#'   \item{ lieu_achat_legumes_frais }{  character }
#'   \item{ lieu_achat_pain }{  character }
#'   \item{ lieu_achat_patisseries }{  character }
#'   \item{ lieu_achat_viandes }{  character }
#'   \item{ lieu_achat_poissons_frais }{  character }
#'   \item{ suivi_instruction_conserv }{  character }
#'   \item{ refroidit_viandes }{  character }
#'   \item{ refroidit_quiches }{  character }
#'   \item{ refroidit_legumes }{  character }
#'   \item{ refroidit_soupes }{  character }
#'   \item{ refroidit_feculents }{  character }
#'   \item{ refroidit_cremesdessert }{  character }
#'   \item{ refroidit_patisseries }{  character }
#'   \item{ fin_conso_platmaison }{  character }
#'   \item{ conso_dlc_jambon }{  character }
#'   \item{ conso_dlc_saumon }{  character }
#'   \item{ conso_dlc_platscuisines }{  character }
#'   \item{ conso_dlc_viandepreemballee }{  character }
#'   \item{ conso_dlc_beurre }{  character }
#'   \item{ conso_apresachat_jamboncoupe }{  character }
#'   \item{ conso_apresachat_autrecharcut }{  character }
#'   \item{ conso_apresachat_platscuisines }{  character }
#'   \item{ conso_apresachat_entreesfroides }{  character }
#'   \item{ conso_apresachat_fromagecoupe }{  character }
#'   \item{ conso_apresachat_viande }{  character }
#'   \item{ temp_frigo }{  character }
#'   \item{ partie_froide_frigo }{  character }
#'   \item{ eaupuits_utilisation }{  character }
#'   \item{ eaupuits_boisson }{  character }
#'   \item{ eaupuits_prepa_repas }{  character }
#'   \item{ eaupuits_arr_jardin }{  character }
#'   \item{ eaupuits_arr_potager }{  character }
#'   \item{ eaupuits_piscine }{  character }
#'   \item{ eaupuits_toilette }{  character }
#'   \item{ eaupuits_wc }{  character }
#'   \item{ eaupuits_lave_linge }{  character }
#'   \item{ eaupuits_boisson_animaux }{  character }
#'   \item{ eaupuits_nettoyage }{  character }
#'   \item{ eaupuits_rien }{  character }
#'   \item{ eaupuits_autre }{  character }
#'   \item{ eaupuits_autre_libelle }{  character }
#'   \item{ eaupuits_nsp }{  character }
#'   \item{ eaupuits_conso_enfant }{  character }
#'   \item{ eaupuits_traitement }{  character }
#'   \item{ eaurobinet }{  character }
#'   \item{ eaurobinet_conso }{  character }
#'   \item{ eaurobinet_traitement }{  character }
#'   \item{ eaurobinet_trait_circeau }{  character }
#'   \item{ eaurobinet_trait_toutcirc }{  character }
#'   \item{ eaurobinet_trait_ptusage }{  character }
#'   \item{ eaurobinet_trait_ptconso }{  character }
#'   \item{ eaurobinet_trait_nsp }{  character }
#'   \item{ trait_carafe }{  character }
#'   \item{ trait_carafe_marque_libelle }{  character }
#'   \item{ trait_carafe_gout }{  character }
#'   \item{ trait_carafe_contaminant }{  character }
#'   \item{ trait_carafe_bacteries }{  character }
#'   \item{ trait_carafe_entartrage }{  character }
#'   \item{ trait_adoucisseur }{  character }
#'   \item{ trait_adoucisseur_gout }{  character }
#'   \item{ trait_adoucisseur_contaminant }{  character }
#'   \item{ trait_adoucisseur_bacteries }{  character }
#'   \item{ trait_adoucisseur_entartrage }{  character }
#'   \item{ trait_cartouche }{  character }
#'   \item{ trait_cartouche_gout }{  character }
#'   \item{ trait_cartouche_contaminant }{  character }
#'   \item{ trait_cartouche_bacteries }{  character }
#'   \item{ trait_cartouche_entartrage }{  character }
#'   \item{ trait_ultraviolet }{  character }
#'   \item{ trait_ultraviolet_gout }{  character }
#'   \item{ trait_ultraviolet_contaminant }{  character }
#'   \item{ trait_ultraviolet_bacteries }{  character }
#'   \item{ trait_ultraviolet_entartrage }{  character }
#'   \item{ trait_cart_refrig }{  character }
#'   \item{ trait_cart_refrig_gout }{  character }
#'   \item{ trait_cart_refrig_contaminant }{  character }
#'   \item{ trait_cart_refrig_bacteries }{  character }
#'   \item{ trait_cart_refrig_entartrage }{  character }
#'   \item{ trait_osmoseur }{  character }
#'   \item{ trait_osmoseur_gout }{  character }
#'   \item{ trait_osmoseur_contaminant }{  character }
#'   \item{ trait_osmoseur_bacteries }{  character }
#'   \item{ trait_osmoseur_entartrage }{  character }
#'   \item{ trait_autre }{  character }
#'   \item{ trait_autre_libelle }{  character }
#'   \item{ trait_autre_gout }{  character }
#'   \item{ trait_autre_contaminant }{  character }
#'   \item{ trait_autre_bacteries }{  character }
#'   \item{ trait_autre_entartrage }{  character }
#'   \item{ trait_nsp }{  character }
#'   \item{ eau_boisson }{  character }
#'   \item{ bouilloire_elec }{  character }
#'   \item{ bouilloire_elec_type }{  character }
#' }
#' @source Inca3
"habitudes_men_decode"
